### ISSUE TITLE
ScanResponse is always busy?

### ISSUE THREAD

**Issue by dingsa0210** [irissmann/arachni-client#4]
I called performScan method, then waited for a while, the response "isBusy()" was alway true?
How should I configure the scan request?

**Comment by irissmann** [comment]
Hi Sam,

sometimes a sercurity scan of your website with Arachni can take a very long time depending on your settings. At first you can try to set a small page limit with `ScopeBuilder.pageLimit()`. But for configuration of the scan please refer the Arachni website.
An other option is to send a shutdown after a timeout and then request the report by one of the getReport methods.
For an example implementation you can also have a look to my Jenkins plugin https://github.com/jenkinsci/arachni-scanner-plugin/blob/master/src/main/java/org/jenkinsci/plugins/arachni/ArachniScanner.java

With kind regards,
Ingo
